Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -52,14 +52,48 @@ jobs:
             with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                
-          - name: Pushes test file
-            uses: dmnemec/copy_file_to_another_repo_action@main
-            env:
-              API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
+          - name: Checkout publish repo
+            uses: actions/checkout@v2
             with:
-              source_file: 'chem_cluster.json'
-              destination_repo: 'sneblina/visualtag'
-              destination_folder: './'
-              user_email: 'example@email.com'
-              user_name: 'dmnemec'
-              commit_message: 'A custom message for the commit'
+              repository: 'sneblina/visualtag'
+              ref: 'test'
+              path: 'publish'
+              persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
+              fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
+
+          - name: Clean publish repo
+            working-directory: 'publish'
+            run: |
+              git rm -rf .
+              git clean -fxd
+          - name: Set up Node.js
+            uses: actions/setup-node@v1
+            with:
+              node-version: '12.x'
+
+          - name: Copy build
+            run: 'cp -r chem_cluster.json publish'
+
+          - name: Check for changes
+            working-directory: publish
+            run: |
+              git add .
+              git status
+              [[ -z $(git status --porcelain) ]] || echo "::set-output name=changed::true"
+            id: check_changes
+
+          - name: Update publish repo
+            if: steps.check_changes.outputs.changed
+            working-directory: publish
+            run: |
+              git config --local user.email "action@github.com"
+              git config --local user.name "GitHub Action"
+              git commit -m "Deploy $GITHUB_SHA"
+          - name: Deploy to Pages
+            if: steps.check_changes.outputs.changed
+            uses: ad-m/github-push-action@v0.6.0
+            with:
+              directory: publish
+              repository: sneblina/visualtag
+              branch: test
+              github_token: ${{ secrets.GITHUB_TOKEN }}
